manifest = "be158528663efd26628afb8c894c263303a6208df077a0eedf89f0a742ffe8e6"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.64.0" ]
revision = "9cbe0f1be39466ec9b76b35b81295959fd417de0"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.64.0" ]
revision = "fea9d446679bef8b8273c3c71c9dbf9af5f4ee1d"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.64.0" ]
revision = "f77b6125bb376584bc51fd31a134d0ad36a9077f"
