manifest = "635d8fd9769c53e3692d6845a20205085fbfab7db15cacae32adc3165acd2b20"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.65.1" ]
revision = "ef899f910b922b982581c55683d22a30ed10e2ab"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.65.1" ]
revision = "dfd1a8c32d76184a8ffe83d63c3a216303dc9085"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.65.1" ]
revision = "6e6c057b13b5f61e6157330ec30fe6cc3e8503b8"
