manifest = "d0df5721292de20fd98928ba1bd3f310288f95bb98c99b6597fd7324ddeee52d"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.44.0" ]
revision = "7ed352e37303fb3af45112ec781b535a943e6a50"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.44.0" ]
revision = "e9c2cb074dc3269ff6ad32c0c998366252920437"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.44.0" ]
revision = "406fa6ff16367868ef87cb3c932d3d4d6bb573ba"
