manifest = "25dd62d4c07a42d22c465876dc503074626d03f90b2be11637a5599bcfbb2809"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.33.1" ]
revision = "fc0cda2c8601a5e6f1371a7d8f5f6152c73d8ad6"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.33.1" ]
revision = "163dee0104360b973f2b5b5dd4f786b991418a90"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.33.1" ]
revision = "ec60ccce30c2d3b0a362500e37817d249aa1114e"
