manifest = "e3096eea8af11599c8cd72969a6ab6c3df055381623045d63ce0fed5ea650d1b"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.61.0" ]
revision = "d1bfb4fc64744904219b6772e1363d4d2302c3a7"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.61.0" ]
revision = "42200144daa6a31d26ad814386f32dad9f546b09"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.61.0" ]
revision = "d25454aaa50d50639af46be51d6698850b021379"
