manifest = "080764e8314ce961838b4155d57bee47f4dfaeea928d5f783b419db406a2a8dc"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.37.0" ]
revision = "382491ee558eb6ed57c07f89b4b2683d16302035"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.37.0" ]
revision = "1cce8dff4e3ef3520b0ce494097cc601383750ca"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.37.0" ]
revision = "4302dffe038e23f3a4c130bae0a3fcc5c90483b0"
